# Form implementation generated from reading ui file '/var/www/db_manager/views/main.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(parent=self.centralwidget)
        self.label.setGeometry(QtCore.QRect(50, 20, 501, 17))
        self.label.setObjectName("label")
        self.showFormAddDb = QtWidgets.QPushButton(parent=self.centralwidget)
        self.showFormAddDb.setGeometry(QtCore.QRect(680, 180, 31, 25))
        self.showFormAddDb.setObjectName("showFormAddDb")
        self.treeFile = QtWidgets.QTreeWidget(parent=self.centralwidget)
        self.treeFile.setGeometry(QtCore.QRect(50, 50, 361, 441))
        self.treeFile.setObjectName("treeFile")
        self.treeFile.headerItem().setText(0, "1")
        self.inputDirPath = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.inputDirPath.setGeometry(QtCore.QRect(50, 510, 261, 25))
        self.inputDirPath.setObjectName("inputDirPath")
        self.btnLoadFiles = QtWidgets.QPushButton(parent=self.centralwidget)
        self.btnLoadFiles.setGeometry(QtCore.QRect(320, 510, 89, 25))
        self.btnLoadFiles.setObjectName("btnLoadFiles")
        self.comboBoxListDb = QtWidgets.QComboBox(parent=self.centralwidget)
        self.comboBoxListDb.setGeometry(QtCore.QRect(440, 140, 311, 25))
        self.comboBoxListDb.setObjectName("comboBoxListDb")
        self.btnExport = QtWidgets.QPushButton(parent=self.centralwidget)
        self.btnExport.setGeometry(QtCore.QRect(440, 390, 151, 25))
        self.btnExport.setObjectName("btnExport")
        self.btnImport = QtWidgets.QPushButton(parent=self.centralwidget)
        self.btnImport.setGeometry(QtCore.QRect(600, 390, 151, 25))
        self.btnImport.setObjectName("btnImport")
        self.label_2 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(440, 110, 131, 17))
        self.label_2.setObjectName("label_2")
        self.inputCurrentFile = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.inputCurrentFile.setGeometry(QtCore.QRect(440, 80, 311, 25))
        self.inputCurrentFile.setObjectName("inputCurrentFile")
        self.label_3 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(440, 50, 141, 17))
        self.label_3.setObjectName("label_3")
        self.btnDeleteRecordDb = QtWidgets.QPushButton(parent=self.centralwidget)
        self.btnDeleteRecordDb.setGeometry(QtCore.QRect(720, 180, 31, 25))
        self.btnDeleteRecordDb.setObjectName("btnDeleteRecordDb")
        self.textBrowser = QtWidgets.QTextBrowser(parent=self.centralwidget)
        self.textBrowser.setGeometry(QtCore.QRect(440, 220, 311, 141))
        self.textBrowser.setObjectName("textBrowser")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 22))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Db Manager"))
        self.label.setText(_translate("MainWindow", "Manager db - import/export database"))
        self.showFormAddDb.setText(_translate("MainWindow", "+"))
        self.btnLoadFiles.setText(_translate("MainWindow", "Load"))
        self.btnExport.setText(_translate("MainWindow", "Export to file"))
        self.btnImport.setText(_translate("MainWindow", "Import to databse"))
        self.label_2.setText(_translate("MainWindow", "Selected Database"))
        self.label_3.setText(_translate("MainWindow", "Selected file"))
        self.btnDeleteRecordDb.setText(_translate("MainWindow", "-"))
