# Form implementation generated from reading ui file 'views/showFormAddDb.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(400, 523)
        self.buttonBox = QtWidgets.QDialogButtonBox(parent=Dialog)
        self.buttonBox.setGeometry(QtCore.QRect(290, 440, 81, 51))
        self.buttonBox.setOrientation(QtCore.Qt.Orientation.Vertical)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.StandardButton.Cancel|QtWidgets.QDialogButtonBox.StandardButton.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.label = QtWidgets.QLabel(parent=Dialog)
        self.label.setGeometry(QtCore.QRect(130, 30, 181, 17))
        self.label.setObjectName("label")
        self.host = QtWidgets.QLineEdit(parent=Dialog)
        self.host.setGeometry(QtCore.QRect(40, 100, 221, 25))
        self.host.setObjectName("host")
        self.label_2 = QtWidgets.QLabel(parent=Dialog)
        self.label_2.setGeometry(QtCore.QRect(40, 70, 67, 17))
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(parent=Dialog)
        self.label_3.setGeometry(QtCore.QRect(40, 130, 67, 17))
        self.label_3.setObjectName("label_3")
        self.port = QtWidgets.QLineEdit(parent=Dialog)
        self.port.setGeometry(QtCore.QRect(40, 160, 221, 25))
        self.port.setObjectName("port")
        self.label_4 = QtWidgets.QLabel(parent=Dialog)
        self.label_4.setGeometry(QtCore.QRect(40, 190, 161, 17))
        self.label_4.setObjectName("label_4")
        self.comboBox = QtWidgets.QComboBox(parent=Dialog)
        self.comboBox.setGeometry(QtCore.QRect(40, 210, 221, 25))
        self.comboBox.setObjectName("comboBox")
        self.db_name = QtWidgets.QLineEdit(parent=Dialog)
        self.db_name.setGeometry(QtCore.QRect(40, 280, 221, 25))
        self.db_name.setObjectName("db_name")
        self.name = QtWidgets.QLineEdit(parent=Dialog)
        self.name.setGeometry(QtCore.QRect(40, 340, 221, 25))
        self.name.setObjectName("name")
        self.label_5 = QtWidgets.QLabel(parent=Dialog)
        self.label_5.setGeometry(QtCore.QRect(40, 250, 121, 17))
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(parent=Dialog)
        self.label_6.setGeometry(QtCore.QRect(40, 310, 121, 17))
        self.label_6.setObjectName("label_6")
        self.db_user = QtWidgets.QLineEdit(parent=Dialog)
        self.db_user.setGeometry(QtCore.QRect(40, 410, 221, 25))
        self.db_user.setObjectName("db_user")
        self.label_7 = QtWidgets.QLabel(parent=Dialog)
        self.label_7.setGeometry(QtCore.QRect(40, 380, 121, 17))
        self.label_7.setObjectName("label_7")
        self.db_password = QtWidgets.QLineEdit(parent=Dialog)
        self.db_password.setGeometry(QtCore.QRect(40, 470, 221, 25))
        self.db_password.setObjectName("db_password")
        self.label_8 = QtWidgets.QLabel(parent=Dialog)
        self.label_8.setGeometry(QtCore.QRect(40, 440, 67, 17))
        self.label_8.setObjectName("label_8")

        self.retranslateUi(Dialog)
        self.buttonBox.accepted.connect(Dialog.accept) # type: ignore
        self.buttonBox.rejected.connect(Dialog.reject) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.label.setText(_translate("Dialog", "Dodaj nowa baze danych"))
        self.label_2.setText(_translate("Dialog", "Host"))
        self.label_3.setText(_translate("Dialog", "Port"))
        self.label_4.setText(_translate("Dialog", "Typ bazy danych"))
        self.label_5.setText(_translate("Dialog", "Baza danych"))
        self.label_6.setText(_translate("Dialog", "Nazwa ogólna"))
        self.label_7.setText(_translate("Dialog", "Użytkownik"))
        self.label_8.setText(_translate("Dialog", "Hasło"))
